### PR TITLE
feat: Migrate CNAME to lerna.js.org

### LINKED ISSUE #68: Migrate to js.org?
> I don't own the domain
https://github.com/lerna/lerna/issues/2033#issuecomment-483394111

js.org offers free subdomains to JavaScript projects https://js.org
It could offer an affordable and easy manage alternative to the `lernajs.io` domain.

### PR DESCRIPTION
**Pull request by ChristianMurphy**
resolves #68

### CODE REVIEW

**Review by evocateur — APPROVED** [review]
Sounds good to me, thanks!

**Comment by evocateur** [comment]
ugh, I think I need to nuke the `CNAME` file to make it possible for the js.org folks to validate it?

**Comment by ChristianMurphy** [comment]
Maybe :man_shrugging:
Their docs list adding cname as step 3 and opening a PR there as step 4. :thinking:
https://github.com/js-org/js.org/pull/2967#issuecomment-483834691 sounds like the change need to be made on the PR to js.org.

**Comment by ChristianMurphy** [comment]
Looks like https://github.com/js-org/js.org/pull/2967#discussion_r276034645 should resolve the comment.

**Comment by evocateur** [comment]
Thanks!

**Pull request merged**
